-- MySQL Script generated by MySQL Workbench
-- Sun Dec  9 19:39:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_catalog_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_catalog_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_catalog_db` DEFAULT CHARACTER SET utf8 ;
USE `my_catalog_db` ;

-- -----------------------------------------------------
-- Table `my_catalog_db`.`Catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Catalog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `About` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Collections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Collections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `About` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(400) NULL,
  `Catalog_id` INT NOT NULL,
  `Brands_id` INT NOT NULL,
  `Collections_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Product_Catalog1`
    FOREIGN KEY (`Catalog_id`)
    REFERENCES `my_catalog_db`.`Catalog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Brands1`
    FOREIGN KEY (`Brands_id`)
    REFERENCES `my_catalog_db`.`Brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Collections1`
    FOREIGN KEY (`Collections_id`)
    REFERENCES `my_catalog_db`.`Collections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Sizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(10) NULL,
  `Width` INT NULL,
  `Height` INT NULL,
  `Lenght` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Designers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Designers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `About` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Fabrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Fabrics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Specimens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Specimens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `Product_id` INT NOT NULL,
  `Sizes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Product_id`),
  CONSTRAINT `fk_Specimens_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `my_catalog_db`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specimens_Sizes1`
    FOREIGN KEY (`Sizes_id`)
    REFERENCES `my_catalog_db`.`Sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Fabrics_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Fabrics_has_Product` (
  `Product_id` INT NOT NULL,
  `Fabrics_id` INT NOT NULL,
  CONSTRAINT `fk_Fabrics_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `my_catalog_db`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fabrics_has_Product_Fabrics1`
    FOREIGN KEY (`Fabrics_id`)
    REFERENCES `my_catalog_db`.`Fabrics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_catalog_db`.`Collections_has_Designers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_catalog_db`.`Collections_has_Designers` (
  `Collections_id` INT NOT NULL,
  `Designers_id` INT NOT NULL,
  CONSTRAINT `fk_Collections_has_Designers_Collections1`
    FOREIGN KEY (`Collections_id`)
    REFERENCES `my_catalog_db`.`Collections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collections_has_Designers_Designers1`
    FOREIGN KEY (`Designers_id`)
    REFERENCES `my_catalog_db`.`Designers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
